In [2]:
import torch


x = torch.arange(12)

x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
# 改变 tensor 形状

X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
X.numel()

12

In [6]:
# 将某一个值设置为 -1，代表这个位置的维度会由其他维度的数量自动计算

Y = x.reshape(2, -1)
Y

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [7]:
# 创建全零 tensor

torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [8]:
'''
例如，当我们构造数组来作
为神经网络中的参数时，我们通常会随机初始化参数的值。以下代码创建一个形状为（3,4）的张量。其中的
每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样。

Returns a tensor filled with random numbers from a normal distribution with 
mean 0 and variance 1 (also called the standard normal distribution).

均值为 0  方差为 1 
'''

torch.randn(3,4)



tensor([[-0.4742,  0.5450, -1.3619,  0.1993],
        [-0.1597,  2.1806, -0.7062, -0.3958],
        [-1.9939,  0.9485,  0.2466,  0.3609]])

In [9]:

# 通过 python 数组创建 tensor

torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])


tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [10]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))

X, X.size()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 torch.Size([3, 4]))

In [11]:
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

Y, Y.size()

(tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 torch.Size([3, 4]))

In [12]:
# 按照第 0 轴，连接两个 tensor
# 两个 [3,4] 的 tensor 合并成 [6,4]

torch.cat((X,Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [13]:
# 按照第 0 轴，连接两个 tensor
# 两个 [3,4] 的 tensor 合并成 [3,8]

torch.cat((X,Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [14]:
# 比较操作，生成一个对应的布尔值的 tensor
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [15]:
# 对张量中的所有元素进行求和，会产生一个单元素张量。

X.sum()

tensor(66.)

In [16]:
# 广播机制


a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [17]:
"""
由于a和b分别是3 x 1和1 x 2矩阵, 如果让它们相加，它们的形状不匹配。我们将两个矩阵广播为一个更大
的3 x 2矩阵, 如下所示： 矩阵 a 将复制列, 矩阵b将复制行, 然后再按元素相加。
"""


a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [18]:
# 切片 slicing

X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [20]:
X[1:3], X

(tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [21]:
# 除读取外，我们还可以通过指定索引来将元素写入矩阵。

X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:

# 其中“:”代表沿轴1（列）的所有元素

X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [23]:
# 使用数组切片节省内存
# 如果我们用 Y = X + Y，我们将取消引用Y指向的张量，
# 而是指向新分配的内存处的张量。

before = id(Y)
Y = Y + X
id(Y) == before

False

In [24]:
# 幸运的是，执行原地操作非常简单。我们可以使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:]
# = <expression>。


before = id(Y)
Y[:] = Y + X
id(Y) == before

True

In [25]:
# tensor 与 numpy 之间的转换

A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [26]:
# 要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数

a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [27]:
# 线性代数

x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [28]:
# 我们通过张量的索引来访问任一元素。

x[3]

tensor(3)

In [29]:

x.shape

torch.Size([4])

In [30]:
# 矩阵

A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [31]:
# 矩阵的转置

A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [32]:
# 对称矩阵

B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [33]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [34]:

X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [35]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [36]:
# 具体而言，两个矩阵的按元素乘法称为Hadamard积（Hadamard product）（数学符号⊙）。

A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [37]:
# 将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。

a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [38]:
# 降维

x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [39]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [40]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [41]:
# 由于输入矩阵沿0轴降维以生成输出向量，因此输入轴0的维数在输出形状中消失。

A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [42]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [43]:
# 沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和。

A.sum(axis=[0, 1]) # 结果和A.sum()相同

tensor(190.)

In [44]:
# 计算平均值

A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [45]:
# 同样，计算平均值的函数也可以沿指定轴降低张量的维度。

A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [46]:
# 非降维求和
# 但是，有时在调用函数来计算总和或均值时保持轴数不变会很有用。

sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]))

In [47]:
# 例如，由于sum_A在对每行进行求和后仍保持两个轴，我们可以通过广播将A除以sum_A。
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [48]:
# 如果我们想沿某个轴计算A元素的累积总和，比如axis=0（按行计算），
# 可以调用cumsum函数。此函数不会沿任何轴降低输入张量的维度。


A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [49]:
# 第 n 行是包括 n 行的所有上方的行的累计和
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [50]:
# 点积

y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)



(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [51]:
# 注意，我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积：

torch.sum(x * y)

tensor(6.)

In [52]:
# 矩阵向量积

A, A.shape, x, x.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 tensor([0., 1., 2., 3.]),
 torch.Size([4]))

In [53]:
torch.mv(A,x)

tensor([ 14.,  38.,  62.,  86., 110.])