reference

https://www.learnpytorch.io/00_pytorch_fundamentals/



In [1]:
import torch
torch.__version__

'2.4.0+cu121'

In [2]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [3]:
# Check the number of dimensions of vector
# 有几个方括号，维数就是几
vector.ndim

1

In [4]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [5]:
# Check number of dimensions
MATRIX.ndim

2

In [6]:
MATRIX.shape

torch.Size([2, 2])

In [7]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [8]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [9]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

![这是图片](./imgs/td.png "dims")

In [10]:
# Create a random tensor of size (3, 4)
# rand 是平均分布生成 0 到 1 之间的数字
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.4144, 0.9532, 0.1031, 0.3241],
         [0.2333, 0.1663, 0.1134, 0.2660],
         [0.8076, 0.6421, 0.5244, 0.3593]]),
 torch.float32)

In [11]:
# 假设您想要一个常见图像形状为[224, 224, 3] （ [height, width, color_channels ]）的随机张量。

random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [12]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [13]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [14]:

'''

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.
有时您可能需要一个数字范围，例如 1 到 10 或 0 到 100。

You can use torch.arange(start, end, step) to do so.
您可以使用torch.arange(start, end, step)来执行此操作。


Where: 在哪里：

start = start of range (e.g. 0)
start = 范围的开始（例如 0
end = end of range (e.g. 10)
end = 范围结束（例如 10
step = how many steps in between each value (e.g. 1)
step = 每个值之间有多少步（例如 1

注意：在Python中，您可以使用range()来创建范围。然而在 PyTorch 中， 
torch.range()已被弃用，并且将来可能会显示错误。

'''


# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:

'''
Sometimes you might want one tensor of a certain type with the same shape as another tensor.
有时您可能需要某种类型的一个张量与另一个张量具有相同的形状。

'''


# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# 数据类型默认是 float32

# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [17]:

float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [18]:
'''
我们之前已经见过这些，但是您想要了解的有关张量的三个最常见属性是：

shape - what shape is the tensor? (some operations require specific shape rules)
shape - 张量是什么形状？ （有些操作需要特定的形状规则）
dtype - what datatype are the elements within the tensor stored in?
dtype - 张量中的元素存储在什么数据类型中？
device - what device is the tensor stored on? (usually GPU or CPU)
device - 张量存储在什么设备上？ （通常是GPU或CPU）
'''

# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.0639, 0.2482, 0.3100, 0.4806],
        [0.8753, 0.4694, 0.1183, 0.2630],
        [0.2658, 0.0549, 0.9563, 0.6777]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [19]:
# 基本操作


# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [20]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [23]:
# 矩阵乘法

# The in-built torch.matmul() method is faster.
# 内置的torch.matmul()方法更快。

# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [22]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [25]:
"""

Neural networks are full of matrix multiplications and dot products.
神经网络充满了矩阵乘法和点积。

The torch.nn.Linear() module (we'll see this in action later on), 
also known as a feed-forward layer or fully connected layer, 
implements a matrix multiplication between an input x and a weights matrix A.

torch.nn.Linear()模块（稍后我们将看到它的实际应用），也称为前馈层或全连接层，实现输入x和权重矩阵A之间的矩阵乘法。

Y = Ax + b

"""


tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)


# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
# 设定种子，固定初始参数
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [26]:
# 求最小值、最大值、平均值、总和等（聚合）

# Create a tensor
x = torch.arange(0, 100, 10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [28]:
# Positional min/max 位置最小/最大

"""
You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.
您还可以分别使用torch.argmax()和torch.argmin()找到出现最大值或最小值的张量的索引。

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).
如果您只想要最高（或最低）值的位置而不是实际值本身（我们将在后面使用softmax 激活函数的部分中看到这一点），这会很有帮助。
"""

# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")



Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [30]:
# 更改张量数据类型

# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype



torch.float32

In [31]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [32]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [34]:
"""
重塑、堆叠、挤压和解压
Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.
很多时候，您需要重塑或更改张量的尺寸，而不实际更改其中的值。


torch.reshape(input, shape)         input重塑为shape 如果兼容  也可以使用torch.Tensor.reshape() 。
Tensor.view(shape)                  返回原始张量的不同shape的视图  但与原始张量共享相同的数据。
torch.stack(tensors, dim=0)         沿新维度 ( dim ) 连接一系列tensors  所有 tensors 必须具有相同的大小。
torch.squeeze(input)                挤压 input 以删除所有值为 1 维度。
torch.unsqueeze(input, dim)         返回在dim处添加维度值为1 input 。
torch.permute(input, dims)          返回原始input的视图 其尺寸排列 重新排列 为dims 。
"""

# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [35]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [36]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723

"""
使用torch.view()更改张量的视图实际上只会创建同一张量的新视图。

So changing the view changes the original tensor too.
因此改变视图也会改变原始张量。

"""
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [37]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [40]:
# 如果我们想将新张量堆叠五次，我们可以使用torch.stack()来实现。

# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([4, 7]))

In [41]:
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.]]),
 torch.Size([7, 4]))

In [42]:
"""
从张量中删除所有单一维度怎么样？

To do so you can use torch.squeeze() (I remember this as squeezing the tensor to only have dimensions over 1).
为此，您可以使用torch.squeeze() （我记得这是将张量压缩为仅具有超过 1 的维度）。

"""

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")




Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [43]:
# 要执行与torch.squeeze()相反的操作，您可以使用torch.unsqueeze()在特定索引处添加维度值 1。

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [44]:
# 您还可以使用torch.permute(input, dims)重新排列轴值的顺序，其中input将转换为具有新dims视图。

# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [45]:
# 索引（从张量中选择数据）

# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [46]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [48]:
# 您还可以使用:指定“此维度中的所有值”，然后使用逗号 ( , ) 添加另一个维度。

# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension

x, x[:, :, 1]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[2, 5, 8]]))

In [55]:
# NumPy array to tensor

# 注意：默认情况下，NumPy 数组是使用数据类型float64创建的，如果将其转换为 PyTorch 张量，它将保留相同的数据类型（如上所述）。

import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [56]:
# 因为我们上面重新分配了tensor ，所以如果更改张量，数组将保持不变。
# Change the array, keep the tensor
array = array + 1
array, tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [50]:
# 如果你想从 PyTorch 张量转到 NumPy 数组，你可以调用tensor.numpy() 。
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [57]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [60]:
# 伪随机


import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [61]:
# 您可以使用torch.cuda.is_available()测试 PyTorch 是否可以访问 GPU。

# Check for GPU
import torch
torch.cuda.is_available()

True

In [62]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [63]:
# 您可以使用torch.cuda.device_count()计算 PyTorch 可以访问的 GPU 数量。

# Count number of devices
torch.cuda.device_count()


1

In [64]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [66]:
# 将张量移回 CPU

# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

Exercises 练习
All of the exercises are focused on practicing the code above.
所有练习都集中于练习上面的代码。

You should be able to complete them by referencing each section or by following the resource(s) linked.
您应该能够通过参考每个部分或遵循链接的资源来完成它们。

Resources: 资源：

Exercise template notebook for 00.
00 的练习模板笔记本。
Example solutions notebook for 00 (try the exercises before looking at this).
00 的示例解决方案笔记本（在看此内容之前尝试练习）。
Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.
文档阅读 - 深度学习（以及一般学习编码）的一个重要部分是熟悉您正在使用的某个框架的文档。在本课程的其余部分中，我们将大量使用 PyTorch 文档。所以我建议花10分钟阅读以下内容（如果你暂时没有明白一些东西也没关系，重点还不是完全理解，而是意识）。请参阅torch.Tensor和torch.cuda的文档。


Create a random tensor with shape (7, 7).
创建形状为(7, 7)随机张量。

Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
对 2 中的张量与另一个形状为(1, 7)的随机张量执行矩阵乘法（提示：您可能需要转置第二个张量）。


Set the random seed to 0 and do exercises 2 & 3 over again.
将随机种子设置为0并再次执行练习 2 和 3。


Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
说到随机种子，我们了解了如何使用torch.manual_seed()设置它，但是有 GPU 等效项吗？ （提示：您需要查看torch.cuda的文档）。如果有，请将 GPU 随机种子设置为1234 。


Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
创建两个形状为(2, 3)的随机张量并将它们发送到 GPU（为此您需要访问 GPU）。创建张量时设置torch.manual_seed(1234) （这不必是 GPU 随机种子）。



Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
对您在 6 中创建的张量执行矩阵乘法（同样，您可能需要调整其中一个张量的形状）。


Find the maximum and minimum values of the output of 7.
求 7 的输出的最大值和最小值。


Find the maximum and minimum index values of the output of 7.
求 7 的输出的最大和最小索引值。


Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
创建一个形状为(1, 1, 1, 10)的随机张量，然后创建一个新的张量，删除所有1维，留下形状为(10)的张量。创建种子时将种子设置为7并打印出第一个张量及其形状以及第二个张量及其形状。

In [67]:

# Create a random tensor with shape (7, 7).
# 创建形状为(7, 7)随机张量。

zeros = torch.zeros(size=(7, 7))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
# 对 2 中的张量与另一个形状为(1, 7)的随机张量执行矩阵乘法（提示：您可能需要转置第二个张量）。

